using Rempart.Core.Json;
using Rempart.Core.Rules;
using Rempart.Core.Snapshots;
using static Rempart.Cli.CliHost;
using static Rempart.Core.Cli.CommandLine;

namespace Rempart.Cli.Commands;

/// <summary>
/// Builds a synthetic fixture from a real capture.
///
/// Fixtures used to be regenerated by a throwaway script that re-parsed the YAML
/// with regular expressions: a second implementation of the loader, neither
/// versioned nor tested, that nobody else could replay. Here the rules loaded by
/// the engine drive the substitution.
/// </summary>
internal static class SynthesiseCommand
{
    public static int Run(string[] args)
    {
        var sourcePath = OptionValue(args, "--from")
            ?? throw new ArgumentException("« synthesise » exige --from <capture>.");
        var outPath = OptionValue(args, "--out")
            ?? throw new ArgumentException("« synthesise » exige --out <fichier>.");

        var profile = OptionValue(args, "--profile") switch
        {
            "hardened" or null => SyntheticProfile.Hardened,
            "defaults" => SyntheticProfile.WindowsDefaults,
            var other => throw new ArgumentException(
                $"Profil inconnu « {other} ». Attendu : hardened, defaults."),
        };

        var deny = OptionValues(args, "--deny");
        var compromised = HasFlag(args, "--compromised");

        var built = SyntheticSnapshot.Build(
            RempartJson.DeserialiseSnapshot(File.ReadAllText(sourcePath)),
            RuleCatalog.Load(RulesDirectory(args)),
            profile,
            machineName: OptionValue(args, "--name") ?? "anon:synthetic",
            domainJoined: HasFlag(args, "--domain-joined"),
            elevated: !HasFlag(args, "--not-elevated"),
            denyPathFragments: deny,
            compromised: compromised);

        File.WriteAllText(outPath, RempartJson.Serialise(built));

        Console.WriteLine($"Fixture écrite : {outPath}");
        Console.WriteLine($"  profil               : {profile}");
        Console.WriteLine($"  lectures             : {built.Registry.Count}");
        Console.WriteLine($"  jointe à un domaine  : {built.SystemInfo?.IsDomainJoined}");
        if (compromised)
        {
            Console.WriteLine("  signes d'intrusion   : plantés (pilote, autorun, port, "
                              + "abonnement WMI, résolveur, extension, tâche)");
        }

        if (deny.Count > 0)
        {
            Console.WriteLine($"  accès refusé sur     : {string.Join(", ", deny)}");
        }

        return 0;
    }
}
