using Rempart.Core.Providers;
using Rempart.Core.Rules;

namespace Rempart.Core.Snapshots;

public enum SyntheticProfile
{
    /// <summary>Every rule sees its key set to the value it expects.</summary>
    Hardened,

    /// <summary>
    /// No hardening key set: the most common case in real fleets, and the one that
    /// exercises the semantics of Windows defaults.
    /// </summary>
    WindowsDefaults,
}

/// <summary>
/// Builds a synthetic snapshot from a real capture, replacing the observed values with
/// the values the rules require.
///
/// Exists because fixtures used to be regenerated by a throwaway script that re-parsed
/// the YAML with regular expressions — a second implementation of the loader, neither
/// versioned nor tested. Here, the rules loaded by the engine itself drive the
/// substitution: a fixture can no longer diverge from the format it is meant to
/// exercise.
/// </summary>
public static class SyntheticSnapshot
{
    public static MachineSnapshot Build(
        MachineSnapshot source,
        IReadOnlyList<Rule> rules,
        SyntheticProfile profile,
        string machineName,
        bool domainJoined = false,
        bool elevated = true,
        IReadOnlyList<string>? denyPathFragments = null)
    {
        var snapshot = new MachineSnapshot
        {
            CapturedAtUtc = "2026-01-01T00:00:00.0000000Z",
            Anonymised = true,
            Registry = new Dictionary<string, RegistryRead>(source.Registry),
            Services = new Dictionary<string, ServiceRead>(source.Services),
            Policy = source.Policy,
            Wmi = new Dictionary<string, WmiRead>(source.Wmi),

            // Copied unchanged from the source capture, which is anonymised. Synthetic
            // profiles vary the configuration judged by the rules, not the persistence
            // inventory: keeping it gives the finding collectors real data to replay,
            // whereas omitting it would make them run on empty input without the replay
            // reporting it.
            ScheduledTasks = source.ScheduledTasks,
            Signatures = new Dictionary<string, FileSignature>(source.Signatures),

            // Drivers are not copied: a healthy machine loads ~190 of them, all validly
            // signed, which would only add benign volume to the fixtures. The cases that
            // matter — unsigned driver, driver on the vulnerable list — are exercised by
            // targeted unit tests, not by a real capture.

            SystemInfo = (source.SystemInfo ?? Fallback) with
            {
                MachineName = machineName,
                IsDomainJoined = domainJoined,
                IsElevated = elevated,
                // Fixed value: a fixture cannot carry a duration that changes.
                UptimeSeconds = 3600,
            },
        };

        foreach (var rule in rules)
        {
            // Only the main check is set, never the applicability condition: some rules
            // are mutually exclusive by construction, and satisfying both sides would
            // produce an inconsistent snapshot.
            Apply(snapshot, rule.Check, profile);
        }

        foreach (var fragment in denyPathFragments ?? [])
        {
            Deny(snapshot, fragment);
        }

        return snapshot;
    }

    private static void Apply(MachineSnapshot snapshot, CheckSpec check, SyntheticProfile profile)
    {
        if (check.Kind == CheckKind.Service)
        {
            ApplyService(snapshot, check, profile);
            return;
        }

        if (check.Kind == CheckKind.Policy)
        {
            ApplyPolicy(snapshot, check, profile);
            return;
        }

        if (check.Kind == CheckKind.Wmi)
        {
            ApplyWmi(snapshot, check, profile);
            return;
        }

        var key = check.Kind == CheckKind.RegistryKey
            ? SnapshotKeys.Existence(check.Path)
            : SnapshotKeys.Value(check.Path, check.ValueName!);

        // Do not invent anything: if the source capture did not see this key, adding it
        // would hide a gap in the capture instead of revealing it.
        if (!snapshot.Registry.ContainsKey(key))
        {
            return;
        }

        snapshot.Registry[key] = profile switch
        {
            SyntheticProfile.WindowsDefaults => RegistryRead.NotFound,
            _ => Satisfying(check),
        };
    }

    /// <summary>
    /// A service has no "Windows default": its state is directly observable. The
    /// "defaults" profile therefore leaves it as the capture saw it, instead of
    /// declaring it absent — which would describe a machine that does not exist.
    /// </summary>
    private static void ApplyService(MachineSnapshot snapshot, CheckSpec check, SyntheticProfile profile)
    {
        if (profile == SyntheticProfile.WindowsDefaults || !snapshot.Services.ContainsKey(check.Path))
        {
            return;
        }

        snapshot.Services[check.Path] = check.Expected?.ToLowerInvariant() switch
        {
            "absent" when check.Operator == CheckOperator.Equals => ServiceRead.NotInstalled,
            _ => ServiceRead.Found(new ServiceInfo(
                check.Path, SatisfyingState(check), SatisfyingStartMode(check))),
        };
    }

    /// <summary>
    /// A policy fact has no "Windows default" either: it is either read or it is not.
    /// The "defaults" profile leaves it as is rather than removing it, which would make
    /// the rule unverifiable instead of non-compliant.
    /// </summary>
    private static void ApplyPolicy(MachineSnapshot snapshot, CheckSpec check, SyntheticProfile profile)
    {
        if (profile == SyntheticProfile.WindowsDefaults || snapshot.Policy is not { } existing)
        {
            return;
        }

        var facts = new Dictionary<string, string>(existing.Values, StringComparer.Ordinal)
        {
            [check.Path] = SatisfyingFact(check),
        };

        snapshot.Policy = existing with { Values = facts };
    }

    private static string SatisfyingFact(CheckSpec check) => check.Operator switch
    {
        // A floor is satisfied by the expected value itself, and so is a ceiling: both
        // comparisons are inclusive.
        CheckOperator.AtLeast or CheckOperator.AtMost or CheckOperator.Equals =>
            check.Expected ?? "0",

        CheckOperator.NotEquals => check.Expected == "0" ? "1" : "0",

        _ => check.Expected ?? "0",
    };

    /// <summary>
    /// A WMI read has no "Windows default" either. The hardened profile writes a single
    /// instance carrying the expected value — otherwise a non-elevated capture, where
    /// WMI denied access, would leave the check "unverifiable" and the fixture would
    /// prove nothing about it.
    /// </summary>
    private static void ApplyWmi(MachineSnapshot snapshot, CheckSpec check, SyntheticProfile profile)
    {
        if (profile == SyntheticProfile.WindowsDefaults || check.ValueName is null)
        {
            return;
        }

        var separator = check.Path.IndexOf(':');
        if (separator < 0)
        {
            return;
        }

        var key = RecordingWmiProvider.Key(
            check.Path[..separator], check.Path[(separator + 1)..], [check.ValueName]);

        snapshot.Wmi[key] = WmiRead.Found([new WmiInstance(
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                [check.ValueName] = SatisfyingFact(check),
            })]);
    }

    private static ServiceState SatisfyingState(CheckSpec check)
    {
        if (!string.Equals(check.ValueName, "state", StringComparison.OrdinalIgnoreCase))
        {
            return ServiceState.Running;
        }

        return check.Operator == CheckOperator.NotEquals
            ? Opposite(Parse(check.Expected, ServiceState.Running))
            : Parse(check.Expected, ServiceState.Running);
    }

    private static ServiceStartMode SatisfyingStartMode(CheckSpec check)
    {
        if (string.Equals(check.ValueName, "state", StringComparison.OrdinalIgnoreCase))
        {
            return ServiceStartMode.Automatic;
        }

        var expected = Parse(check.Expected, ServiceStartMode.Automatic);

        return check.Operator == CheckOperator.NotEquals
            ? expected == ServiceStartMode.Disabled ? ServiceStartMode.Automatic : ServiceStartMode.Disabled
            : expected;
    }

    private static ServiceState Opposite(ServiceState state) =>
        state == ServiceState.Running ? ServiceState.Stopped : ServiceState.Running;

    private static T Parse<T>(string? raw, T fallback) where T : struct, Enum =>
        Enum.TryParse<T>(raw, ignoreCase: true, out var parsed) ? parsed : fallback;

    /// <summary>Value that makes the check pass.</summary>
    private static RegistryRead Satisfying(CheckSpec check) => check.Operator switch
    {
        CheckOperator.Absent => RegistryRead.NotFound,
        CheckOperator.Exists => RegistryRead.Found(RegistryValue.OfNumber(1)),

        // The opposite of the rejected value. Defaulting to 0 is enough, except when 0
        // is precisely the rejected value.
        CheckOperator.NotEquals => RegistryRead.Found(
            RegistryValue.OfNumber(check.Expected == "0" ? 1 : 0)),

        // A ceiling is satisfied by zero, unless the ceiling is itself negative.
        CheckOperator.AtMost => RegistryRead.Found(RegistryValue.OfNumber(
            long.TryParse(check.Expected, out var cap) && cap < 0 ? cap : 0)),

        _ when check.Kind == CheckKind.RegistryKey => RegistryRead.Found(RegistryValue.OfNumber(1)),

        _ => long.TryParse(check.Expected, out var number)
            ? RegistryRead.Found(RegistryValue.OfNumber(number))
            : RegistryRead.Found(RegistryValue.OfText(check.Expected ?? string.Empty)),
    };

    /// <summary>
    /// Simulates access denied on keys whose path contains the given fragment. Used to
    /// produce a non-elevated scan fixture.
    /// </summary>
    private static void Deny(MachineSnapshot snapshot, string fragment)
    {
        foreach (var key in snapshot.Registry.Keys
                     .Where(k => k.Contains(fragment, StringComparison.OrdinalIgnoreCase))
                     .ToList())
        {
            snapshot.Registry[key] = RegistryRead.AccessDenied;
        }
    }

    private static readonly SystemInfo Fallback = new(
        MachineName: "anon:synthetic",
        OsVersion: "10.0.26200.0",
        Is64BitOperatingSystem: true,
        IsElevated: true,
        ProcessorCount: 8,
        UptimeSeconds: 3600,
        FirmwareType: "uefi");
}
